vim.pack.add({
  "https://github.com/nvim-lua/plenary.nvim",
  "https://github.com/nvim-telescope/telescope.nvim",
  "https://github.com/nvim-treesitter/nvim-treesitter",
  "https://github.com/tpope/vim-fugitive",
  "https://github.com/nvim-tree/nvim-web-devicons",
  "https://github.com/mathofprimes/nightvision-nvim",
  "https://github.com/Aasim-A/scrollEOF.nvim",
})
